<a href="https://colab.research.google.com/github/TapanManu/Pytorch-Intro/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [0]:
t1.dtype


torch.float32

In [0]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [0]:
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [0]:
t4=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
t4

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [0]:
t1.shape


torch.Size([])

In [0]:
t2.shape

torch.Size([4])

In [0]:
t3.shape

torch.Size([3, 2])

In [0]:
t4.shape


torch.Size([2, 2, 2])

In [0]:
import numpy as np
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [0]:
y=np.array([1,2])
y

array([1, 2])

In [0]:
z=torch.from_numpy(x)
z

tensor([[1, 2],
        [3, 4]])

In [0]:
a=torch.tensor([3.])
b=torch.tensor(4.,requires_grad=True)
c=torch.tensor(5.,requires_grad=True)

In [0]:
d=b+1

In [0]:
d.backward()

In [0]:
print (a.grad)
print (b.grad)
print (c.grad)

None
tensor(13.)
tensor(4.)
