<a href="https://colab.research.google.com/github/TapanManu/Pytorch-Intro/blob/master/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

In [0]:
#input(temp,rainfall,humidity)
inputs=np.array([[73,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70]],dtype='float32')

In [0]:
#target(apples,oranges)
targets=np.array([[56,70],
                 [81,101],
                 [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [0]:
input=torch.from_numpy(inputs)
target=torch.from_numpy(targets)
print (input)
print (target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [0]:
#randomly generating weights w and biases b
#w=[[w11,w12,w13],[w21,w22,w23]]
#b=[b1,b2]
#making predictive models
#apples=w11*temp+w12*rainfall+w13*humidity+b1
#oranges=w21*temp+w22*rainfall+w23*humidity+b2
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.2538, -0.8042,  0.0013],
        [ 0.1547, -1.2781, -0.4894]], requires_grad=True)
tensor([-2.0087, -0.3845], requires_grad=True)


In [0]:
def model(x):
  return x @ w.t()+b

In [0]:
#generate predictions
preds=model(input)
print(preds)

tensor([[ -37.3060,  -95.7726],
        [ -49.5981, -130.1071],
        [ -87.6167, -186.5841],
        [ -10.6511,  -57.6741],
        [ -61.6082, -146.6723]], grad_fn=<AddBackward0>)


In [0]:
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [0]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [0]:
#calculate loss
loss=mse(preds,target)
print(loss)

tensor(35918.4297, grad_fn=<DivBackward0>)


In [0]:
loss.backward()

In [0]:
print(w)
print(w.grad)

tensor([[ 0.2538, -0.8042,  0.0013],
        [ 0.1547, -1.2781, -0.4894]], requires_grad=True)
tensor([[-10271.9600, -12527.4326,  -7416.9746],
        [-17784.8223, -20768.7969, -12510.9922]])


In [0]:
#adjust weights and gradients
with torch.no_grad():
  w-=w.grad * 1e-5
  b-=b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()
  

In [0]:
print(w)
print(b)

tensor([[ 0.3565, -0.6790,  0.0755],
        [ 0.3326, -1.0705, -0.3643]], requires_grad=True)
tensor([-2.0075, -0.3824], requires_grad=True)


In [0]:
preds=model(input)
loss=mse(preds,target)
print(loss)

tensor(24793.4746, grad_fn=<DivBackward0>)


In [0]:
#train for 100 epochs
for i in range(100):
  preds=model(input)
  loss=mse(preds,target)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
  

In [0]:
print(loss)

tensor(0.5717, grad_fn=<DivBackward0>)


In [0]:
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [0]:
print(preds)

tensor([[ 56.8376,  70.2765],
        [ 82.3424, 100.4490],
        [118.9050, 133.5125],
        [ 21.1680,  37.1756],
        [101.7094, 118.5846]], grad_fn=<AddBackward0>)


In [0]:
import torch.nn as nn

In [0]:
inputs=np.array([[73,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70]],dtype='float32')
targets=np.array([[56,70],
                 [81,101],
                 [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [0]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [0]:
from torch.utils.data import TensorDataset

In [0]:
#define datasets
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [0]:
from torch.utils.data import DataLoader

In [0]:
#define dataloader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [0]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[103., 119.],
        [ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.],
        [119., 133.]])


In [0]:
#define model
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0489, -0.4219, -0.0593],
        [ 0.2907,  0.4363, -0.3230]], requires_grad=True)
Parameter containing:
tensor([ 0.5712, -0.1159], requires_grad=True)


In [0]:
print(model.parameters())

<generator object Module.parameters at 0x7f6282b63678>


In [0]:
#import nn.functional
import torch.nn.functional as F

In [0]:
#define loss function
loss_fn=F.mse_loss

In [0]:
loss=loss_fn(model(inputs),targets)
print (loss)

tensor(9743.6650, grad_fn=<MseLossBackward>)


In [0]:
#define optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [0]:
#utility function to train the model
def fit(num_epochs,model,loss_fn,opt):
  #repeat for given number of epochs
  for epoch in range(num_epochs):
    #train with batches of data
    for xb,yb in train_dl:
      #1.generate predictions
      pred=model(xb)
      #2.calculate loss
      loss=loss_fn(pred,yb)
      #3.compute gradients
      loss.backward()
      #4.update parameters using gradients
      opt.step()
      #5.reset the gradients to zero
      opt.zero_grad()
      #print the progress
      if(epoch+1)%10==0:
        print('Epoch[{}/{}],loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))
      

In [0]:
fit(100,model,loss_fn,opt)

Epoch[10/100],loss:0.5414
Epoch[20/100],loss:0.5410
Epoch[30/100],loss:0.5406
Epoch[40/100],loss:0.5403
Epoch[50/100],loss:0.5399
Epoch[60/100],loss:0.5396
Epoch[70/100],loss:0.5392
Epoch[80/100],loss:0.5389
Epoch[90/100],loss:0.5386
Epoch[100/100],loss:0.5383


In [0]:
print (preds)
print (targets)

tensor([[ 56.8376,  70.2765],
        [ 82.3424, 100.4490],
        [118.9050, 133.5125],
        [ 21.1680,  37.1756],
        [101.7094, 118.5846]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
